flowchart TD
    subgraph FuA["Fuentes de Energía"]
        SP[Panel Solar 5V]
        BATT[(Batería LiPo 3.7V 1000mAh)]
    end

    subgraph Heltec["Módulo Heltec WiFi LoRa 32"]
        CH[Controlador de Carga]
        ESP[ESP32 SoC]
        OLED[Pantalla OLED]
        LoRa[Chip LoRa]
        
        CH -->|"Alimenta (3.3V)"| ESP
        ESP --- OLED
        ESP --- LoRa
    end

    SP -->|"USB (5V)"| CH
    BATT <-->|"Conector JST (3.7V)"| CH

    subgraph Sens["Sensores Ambientales"]
        L[Sensor de Luz BH1750]
        H[Humedad del Suelo]
        T[Temperatura DS18B20]
    end

    L -- "I2C" --> ESP
    H -- "Analógico (ADC)" --> ESP
    T -- "OneWire" --> ESP
    
    LoRa -- "Cable U.FL" --> Ant((Antena Externa LoRa))
